version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "25000:5432"
    environment:
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: Mackenzie123.
      POSTGRES_DB: postgre
    volumes:
      - ./data:/var/lib/postgresql/data
    dns:
      - 8.8.8.8
      - 1.1.1.1

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgre
      SPRING_DATASOURCE_USERNAME: seu_usuario
      SPRING_DATASOURCE_PASSWORD: Mackenzie123.
    restart: unless-stopped